### ISSUE TITLE
如果打开demo，立刻打开相册选取图片后，会闪退app，提示如下信息：

### ISSUE THREAD

**Issue by xuhongv** [chaychan/AndroidNAdaption#1]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                   at java.io.File.fixSlashes(File.java:185)
                                                                                   at java.io.File.<init>(File.java:134)
                                                                                   at com.chaychan.androidnadaption.MainActivity.onActivityResult(MainActivity.java:166)

**Comment by chaychan** [comment]
@xuhongv 已经修复了，多谢反馈

**Comment by xuhongv** [comment]
你这个不可以在fragment用哦

**Comment by chaychan** [comment]
@xuhongv Fragment的话就检查权限和申请权限的方法的调用修改下而已

**Comment by xuhongv** [comment]
您没有说明呢：
如果是Activity 就这样：
                ActivityCompat.requestPermissions((Activity) mContext, permissionList.toArray(new String[permissionList.size()]), 1);
    如果在fragment就这样：
                mFragment.requestPermissions(permissionList.toArray(new String[permissionList.size()]), 1);

**Comment by chaychan** [comment]
@xuhongv 这个检查和申请权限的API，Activity和Fragment中有所不同，相信不清楚的人会自己百度一下就知道的
